apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment-deployment
spec:
  selector:
    matchLabels:
      app: amassnao
  replicas: 1
  template:
    metadata:
      labels:
        app: amassnao
    spec:
      containers:
      - name: playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: playground-deployment-service
spec:
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    run: playground-deployment-deployment